### PR TITLE
Add a default mimeapps.list file

### PR DESCRIPTION
**Pull request by EbonJaeger**
This should solve the issue where programs get installed that register
as the handler for MIME types that they shouldn't, for example, VS Code
and directories.

Adapted from Debian's default mimeapps list for gnome-session.

Ref https://github.com/getsolus/packages/issues/1470

Signed-off-by: Evan Maddock <maddock.evan@vivaldi.net>

### CODE REVIEW

**Comment by ReillyBrogan** [comment]
Are all of these applications part of a default GNOME install?

**Comment by sebo505** [comment]
At least org.gnome.TextEditor.desktop isn't part of default installation of GNOME Solus edition. We ship gedit instead.
But mimeapps.list always mentions TextEditor together with gedit.

**Comment by sebo505** [comment]
abiword.desktop isn't installed either.

**Comment by ReillyBrogan** [comment]
Yeah at least firefox lists firefox-esr which we don't ship (though it falls back to regular firefox).

**Comment by ReillyBrogan** [comment]
> abiword.desktop isn't installed either. Nor is libreoffice-math.desktop. I am unsure concerning org.gnome.font-viewer.desktop.

An application doesn't need to be installed to be the default mime handler. It just means that when/if it it installed it will become the default handler. On Plasma I know that it will integrate with package installation via packagekit so that if you try to open a file where the default handler is not installed it will prompt you to install the appropriate package. I'm not sure how GNOME handles that.

**Pull request merged**
